name: livescore_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  get: 4.6.5
  http: ^0.13.4
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
    - assets/svg/